# Generated by Django 3.0.8 on 2021-12-06 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('myWeb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Citizen',
            fields=[
                ('citizen_id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='Hole',
            fields=[
                ('hole_id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('hole_street', models.CharField(max_length=20)),
                ('hole_location', models.CharField(max_length=20)),
                ('hole_size', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('name', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=32)),
                ('type', models.CharField(max_length=32)),
            ],
        ),
    ]
