# Generated by Django 3.0.8 on 2021-12-07 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myWeb', '0002_citizen_hole_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='hole',
            name='hole_distinct',
            field=models.CharField(default='Baiyun', max_length=32),
        ),
        migrations.AddField(
            model_name='hole',
            name='hole_priority',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='hole',
            name='hole_status',
            field=models.CharField(default='waiting_for_repair', max_length=32),
        ),
        migrations.AlterField(
            model_name='hole',
            name='hole_location',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='hole',
            name='hole_street',
            field=models.CharField(max_length=32),
        ),
    ]
