# Generated by Django 3.0.8 on 2021-12-07 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myWeb', '0003_auto_20211207_1023'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='citizen',
            name='citizen_id',
        ),
        migrations.AddField(
            model_name='hole',
            name='citizen_name',
            field=models.CharField(default=' ', max_length=32),
        ),
        migrations.AlterField(
            model_name='citizen',
            name='name',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
